### PR TITLE
Laravel 10.x Shift

### PR DESCRIPTION
**Pull request by uyscuti-wiki**
This pull request includes the changes for upgrading to Laravel 10.x. Feel free to commit any additional changes to the `shift-109666` branch.

**Before merging**, you need to:

- Checkout the `shift-109666` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator), [no CI?](https://laravelshift.com/ci-generator))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts).

### CODE REVIEW

**Comment by uyscuti-wiki** [comment]
:x: Shift could not upgrade the following files since they differed from the default Laravel version. You will need to compare these files against the [default Laravel 10 versions](https://github.com/laravel-shift/laravel-10.x/) and merge any changes:

- [ ] lang/en/validation.php

**Comment by uyscuti-wiki** [comment]
:warning: Shift upgraded your configuration files by defaulting them and merging your _true customizations_. These include values which are not changeable through core `ENV` variables.

You should [review this commit](https://github.com/ddlibrary/ddlibrary/pull/291/commits/67329b645ee58400e46ffc8d52958e04eed512ae?w=1) for additional customizations or opportunities to use new `ENV` variables. If you have a lot of customizations, you may undo this commit with `git revert 67329b64` and make the [config file changes](https://github.com/laravel-shift/laravel-9.x/pull/4/commits/5401110f1f41793ecdce268495768abfa4a53dfe) manually.

**Comment by uyscuti-wiki** [comment]
:information_source: Laravel 10 now verifies hashed values were created by the same hashing algorithm. If your application has hashed values created by different hashing algorithms, you may set the `verify` option to `false` in your hashing configuration. For more details, you may review the [original PR](https://github.com/laravel/laravel/pull/6258).

**Comment by uyscuti-wiki** [comment]
:information_source: Shift [updated your dependencies](https://github.com/ddlibrary/ddlibrary/pull/291/commits/2e1c0aaa4998a6cbbbb945da4b8af6f4ee24a5a3?w=1) for Laravel 10. While many of the popular packages are reviewed, you may have to update additional packages in order for your application to be compatible with Laravel 10. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling any Composer issues.

The following dependencies were updated by a major version and may have their own changes. You may check their changelog for any additional upgrade steps.

- [ ] [laravel/ui](https://packagist.org/packages/laravel/ui)
- [ ] [yajra/laravel-datatables-oracle](https://packagist.org/packages/yajra/laravel-datatables-oracle)

**Comment by uyscuti-wiki** [comment]
:information_source: Shift detected your application has a test suite. To make verifying the upgrade easier, Shift did not upgrade your testing dependencies for PHPUnit 10. Once you have completed your upgrade, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free to upgrade your test suite to PHPUnit 10 separately.

**Comment by uyscuti-wiki** [comment]
:information_source: Laravel renamed the `password_resets` table to `password_reset_tokens`. While an optional change, Shift detected you have a migration for this table and [created a migration](https://github.com/ddlibrary/ddlibrary/pull/291/commits/bcd0de5a45738d839944609eef194191ab48df50?w=1) to rename it as well as updated the reference in your `config/auth.php` file. You should check for any additional references to this table and run `php artisan migrate` to complete your upgrade.

**Comment by uyscuti-wiki** [comment]
:information_source: Laravel 10 added PHP type hints to all user-land code included in a new Laravel application. In an effort to modernize your code, Shift [added type hints](https://github.com/ddlibrary/ddlibrary/pull/291/commits/f7614a2e25f5ccafcd587ec2de99e1a0a1118d03?w=1) to any method which is used by Laravel.

**Comment by uyscuti-wiki** [comment]
:information_source: Now with type hints in your code, defining types within PHP DocBlocks is redundant. Laravel has removed all of the `@param` and `@return` tags from its DocBlocks where types are defined with PHP. Similarly, Shift [removed these tags](https://github.com/ddlibrary/ddlibrary/pull/291/commits/81a56d3fc69a7b19f7b3c7c249d59578902e9a4a?w=1) from any DocBlock where the code now has _equivalent_ type hints.

**Comment by uyscuti-wiki** [comment]
:information_source: Shift understands developers have different preferences when it comes to type hints. All of Shift's automation is done in nice, atomic commits. This makes it easier to undo any of the changes Shift makes.

If you wish to undo the changes relating to type hints, you may run:

- `git revert 81a56d3` to revert the DocBlock changes.
- `git revert 0ef07fe` to revert the type hints added from DocBlocks.
- `git revert f7614a2` to revert the type hints added for Laravel 10.

**Comment by uyscuti-wiki** [comment]
:warning: In Laravel 10 you may no longer implicitly cast a `DB::raw()` expression to a string. Instead, you must retrieve the string value from the expression using the `getValue()` method. Query builder methods will continue to automatically handle `DB::raw()` expressions as before. This change only affects instances where you are using `DB::raw()` expressions in your own code.

Shift detected calls to `DB::raw()`. You should review these instances to see if you are attempting to use them as a string.

- [ ] app/DownloadCount.php
- [ ] app/Resource.php
- [ ] app/ResourceView.php
- [ ] app/User.php
- [ ] database/migrations/2019_04_16_233711_create_password_resets_table.php

**Comment by uyscuti-wiki** [comment]
:information_source: All of the underlying Symfony components used by Laravel have been upgraded to Symfony 6.2. Shift detected references to Symfony classes within your application. You should review the [Symfony change log](https://github.com/symfony/symfony/blob/6.2/UPGRADE-6.2.md) for any additional changes.

**Comment by uyscuti-wiki** [comment]
:information_source: The `app/Models` folder was reintroduced in Laravel 8. This was an _optional_ change. Laravel and the `artisan` commands will automatically detect if you are using the `app/Models` folder or not.

If you wish to modernize your application to use the `app/Models` folder, you may run the [Namespace Models Shift](https://laravelshift.com/laravel-namespace-models) for free.

**Comment by uyscuti-wiki** [comment]
:information_source: Laravel began using Vite to build frontend assets in Laravel 9.19. While you may continue to use Laravel Mix, it is no longer the default. If you wish to modernize your application to use Vite, you may run the [Vite Converter](https://laravelshift.com/convert-laravel-mix-to-vite) for free.

**Comment by uyscuti-wiki** [comment]
:tada: Congratulations, you're now running the latest version of Laravel!

Next, you may optionally run the following _Shifts_ to ensure your application is fully upgraded, adopts the latest Laravel conventions, and easier to maintain in the future:

- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automatically updates your code to the latest Laravel conventions.
- [Tests Generator](https://laravelshift.com/laravel-test-generator) intelligently generates model factories, HTTP Tests, and configuration for your application.
- [CI Generator](https://laravelshift.com/ci-generator) intelligently generates CI jobs to lint PHP, check code style, and run tests, including Dusk.

You may also use the [Shift Workbench](https://laravelshift.com/workbench) to automate common tasks for maintaining your Laravel and PHP applications.

**Review by azizullahsaeidi — APPROVED** [review]

**Pull request merged**
